In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances

### CONSTANT ###

EDGE_WEIGHT_CONST = 0.4

In [4]:
def obtain_vector(df, node_id):
    return np.array(list(df.loc[node_id][6:-2]))

In [5]:
def compute_edge_weights(df, w=EDGE_WEIGHT_CONST):
    """
    input:
    flow1: feature vector of flow1
    flow2: feature vector of flow2
    w: weight parameter (0 -> 1)
    direct_conn: whether there is a direct connection between flow1 and flow2
    
    """
    df.drop(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port','Protocol'
                             , 'Activity', 'Label'], axis=1, inplace=True)
    X = df.values
    
    
#     direct_conn = 0
#     if (flow1['Src IP'] == flow2['Src IP'] and flow1['Dst IP'] == flow2['Dst IP']):
#         direct_conn = 1
        
#     f1 = np.array(list(flow1[6:-2]))
#     f2 = np.array(list(flow2[6:-2]))
    
    
    adj = w*cosine_similarity(X) #+ (1-w)*direct_conn
    
    return adj

In [6]:
traffic = pd.read_csv('/home/tuanphu9249/HonoursResearch/Data/Datasets/DAPT2020/data_custom_reconnaissance.csv',
                      float_precision='round_trip')

print("Number of flows: ", traffic.shape[0])
print("Number of features: ", traffic.shape[1])

Number of flows:  29254
Number of features:  85


In [7]:
columns = ['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Activity', 'Label']

traffic.columns = columns
pd.set_option('display.max_colwidth', None)
traffic.head()

Flow ID        Src IP  Src Port  \
0     192.168.3.29-35.222.85.5-40250-80-6  192.168.3.29     40250   
1              0.87.248.248-3.0.0.0-0-0-0  0.87.248.248         0   
2                   8.0.6.4-8.6.0.1-0-0-0       8.6.0.1         0   
3        255.255.255.255-0.0.0.0-67-68-17       0.0.0.0        68   
4  192.168.3.10-239.2.11.71-53569-8662-17  192.168.3.10     53569   

            Dst IP  Dst Port  Protocol               Timestamp  Flow Duration  \
0      35.222.85.5        80         6  16/07/2019 11:57:20 AM         109576   
1          3.0.0.0         0         0  16/07/2019 11:54:58 AM      119999725   
2          8.0.6.4         0         0  16/07/2019 11:57:01 AM      119999082   
3  255.255.255.255        67        17  16/07/2019 11:57:01 AM      119308004   
4      239.2.11.71      8662        17  16/07/2019 11:57:09 AM      114861346   

   Tot Fwd Pkts  Tot Bwd Pkts  ...  Active Mean    Active Std  Active Max  \
0             3             5  ...          0.0  0.000000e+00         0.0   
1             2             1  ...          0.0  0.000000e+00         0.0   
2           244             1  ...          0.0  0.000000e+00         0.0   
3            90             1  ...          0.0  0.000000e+00         0.0   
4            31             1  ...    2814192.6  2.523818e+06   5479718.0   

   Active Min     Idle Mean      Idle Std    Idle Max    Idle Min  Activity  \
0         0.0  0.000000e+00  0.000000e+00         0.0         0.0    Normal   
1         0.0  5.999986e+07  5.020458e+01  59999898.0  59999827.0    Normal   
2         0.0  0.000000e+00  0.000000e+00         0.0         0.0    Normal   
3         0.0  0.000000e+00  0.000000e+00         0.0         0.0    Normal   
4        64.0  1.439863e+07  3.619735e+06  20017321.0   8472883.0    Normal   

    Label  
0  BENIGN  
1  BENIGN  
2  BENIGN  
3  BENIGN  
4  BENIGN  

[5 rows x 85 columns]

In [8]:
# Remove duplicate entries
traffic.drop_duplicates(subset=None, keep='first', inplace=True, ignore_index=False)

# reformat Timestamp to Unix time
# traffic[' Timestamp'] = pd.to_datetime(traffic[' Timestamp'])
# traffic[' Timestamp']= traffic[' Timestamp'].values.astype(np.int64) // 10 ** 9

# remove Timestamp column
traffic = traffic.drop(columns=['Timestamp'])

# Remove constant columns
traffic = traffic.loc[:, traffic.apply(pd.Series.nunique) != 1]

# Remove column with NaN or Inf
traffic = traffic[~traffic.isin([np.nan, np.inf, -np.inf]).any(1)]

In [9]:
print("Number of flows: ", traffic.shape[0])
print("Number of features: ", traffic.shape[1])
traffic.head()

Number of flows:  29254
Number of features:  72


Flow ID        Src IP  Src Port  \
0     192.168.3.29-35.222.85.5-40250-80-6  192.168.3.29     40250   
1              0.87.248.248-3.0.0.0-0-0-0  0.87.248.248         0   
2                   8.0.6.4-8.6.0.1-0-0-0       8.6.0.1         0   
3        255.255.255.255-0.0.0.0-67-68-17       0.0.0.0        68   
4  192.168.3.10-239.2.11.71-53569-8662-17  192.168.3.10     53569   

            Dst IP  Dst Port  Protocol  Flow Duration  Tot Fwd Pkts  \
0      35.222.85.5        80         6         109576             3   
1          3.0.0.0         0         0      119999725             2   
2          8.0.6.4         0         0      119999082           244   
3  255.255.255.255        67        17      119308004            90   
4      239.2.11.71      8662        17      114861346            31   

   Tot Bwd Pkts  TotLen Fwd Pkts  ...  Active Mean    Active Std  Active Max  \
0             5             87.0  ...          0.0  0.000000e+00         0.0   
1             1              0.0  ...          0.0  0.000000e+00         0.0   
2             1              0.0  ...          0.0  0.000000e+00         0.0   
3             1          26092.0  ...          0.0  0.000000e+00         0.0   
4             1           1576.0  ...    2814192.6  2.523818e+06   5479718.0   

   Active Min     Idle Mean      Idle Std    Idle Max    Idle Min  Activity  \
0         0.0  0.000000e+00  0.000000e+00         0.0         0.0    Normal   
1         0.0  5.999986e+07  5.020458e+01  59999898.0  59999827.0    Normal   
2         0.0  0.000000e+00  0.000000e+00         0.0         0.0    Normal   
3         0.0  0.000000e+00  0.000000e+00         0.0         0.0    Normal   
4        64.0  1.439863e+07  3.619735e+06  20017321.0   8472883.0    Normal   

    Label  
0  BENIGN  
1  BENIGN  
2  BENIGN  
3  BENIGN  
4  BENIGN  

[5 rows x 72 columns]

In [10]:
print("Number of Benign flows: ", list(traffic['Label']).count('BENIGN'))
print("Number of Reconnaissance flows: ", list(traffic['Label']).count('Reconnaissance'))

Number of Benign flows:  24849
Number of Reconnaissance flows:  4405


In [11]:
node_ids = list(traffic.index)
num_nodes = len(node_ids)

In [12]:
# compute_edge_weight(traffic.iloc[1], traffic.iloc[10])
f1 = obtain_vector(traffic, 1)
f2 = obtain_vector(traffic, 2)
f3 = obtain_vector(traffic, 3)
f4 = obtain_vector(traffic, 4)



In [13]:
# compute_edge_weights(traffic)
traffic.drop(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port','Protocol'
                             , 'Activity', 'Label'], axis=1, inplace=True)


In [29]:
X = traffic.values
print(cosine_similarity(X[1:6]))

[[0.5724977]]
[[1.         0.5724977  0.58535252 0.6973482  0.67752541]
 [0.5724977  1.         0.99952488 0.97122795 0.59295453]
 [0.58535252 0.99952488 1.         0.97599687 0.60627839]
 [0.6973482  0.97122795 0.97599687 1.         0.71610205]
 [0.67752541 0.59295453 0.60627839 0.71610205 1.        ]]


In [20]:
adj_matrix(traffic, num_nodes)

NameError: name 'adj_matrix' is not defined